# Generated by Django 4.2.4 on 2023-09-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0003_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_id', models.IntegerField()),
                ('emp_age', models.IntegerField()),
            ],
        ),
    ]
