# Generated by Django 4.2.4 on 2023-09-16 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.IntegerField(verbose_name=123)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('behaviour', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m1', models.IntegerField()),
                ('m2', models.IntegerField()),
                ('m3', models.IntegerField()),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.student')),
            ],
        ),
    ]
