# Generated by Django 4.2.4 on 2023-09-15 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='print',
            new_name='price',
        ),
    ]
